
# Python 中如何优雅的连接数据库

## 一般链接

```python

from sqlalchemy import create_engine, select, delete, update
from sqlalchemy.orm import Session,sessionmaker, DeclarativeBase, mapped_column, Mapped
from sqlalchemy import Column, Integer, String
from sqlalchemy.exc import SQLAlchemyError


DATABASE_URL = "sqlite:///test_case.db"
engine = create_engine(DATABASE_URL, pool_size=10, max_overflow=20) # 使用连接池，如果移除pool_size, max_overfolw，将使用queue

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def get_db():
    with SessionLocal() as session:
        return session

db = get_db()

```


## 使用fastapi，依赖注入

首先样例仅供参考，因为fastapi要求返回的值类型与自定义值类型目前存在不兼容的情况，根据issus中的问题可能是fastapi没有兼容sqlalchemy导致，可能以后会修复(目前 2023/10/20)

在上述基础上修改方法为yield返回

```python
from fastapi import Depends, FastAPI, HTTPException, Response, Request

import uvicorn

app = FastAPI()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


Base = declarative_base()

class User(Base):
    __tablename__ = "users" # 指定表名

    id:Mapped[int] = mapped_column(primary_key=True)
    name:Mapped[str] = mapped_column(nullable=True)
    age:Mapped[int] = mapped_column(nullable=False)

@app.get("/get_all_users/")
async def get_all_users(db: Session = Depends(get_db)):
    try:
        # 使用数据库连接执行操作
        testcases = db.query(User).all()
        return testcases
    except SQLAlchemyError as e:
        raise HTTPException(status_code=500, detail="Database error" + "\n" + str(e))

```
